database:
  server: "cc-sql16-vcsa\\vcsa"
  dbname: "DATAMART"
  driver: "{SQL Server}"
  trusted_connection: true

output_paths:
  current_students: "output/current_students"
  alumni: "output/alumni"
  mapping_codes: "output/mapping_codes"


